version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10
  cli: circleci/circleci-cli@0.1

executors:
  linter:
    resource_class: small
    docker:
      - image: cytopia/yamllint:1.23
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD

jobs:
  lint:
    executor: linter
    steps:
      - checkout
      - run:  yamllint --no-warnings -d relaxed .
  publish:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/pack:
          use-orb-pack: true
      - orb-tools/publish:
          orb-ref: entur/salg-btd@dev:$CIRCLE_BRANCH
      - orb-tools/increment:
          orb-ref: entur/salg-btd@dev:$CIRCLE_BRANCH

workflows:
  verify:
    jobs:
      - lint
      - publish:
          requires:
            - lint
          context: orb-publishing
          filters:
            branches:
              only: master
