version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0.1

executors:
  linter:
    resource_class: small
    docker:
      - image: cytopia/yamllint:1.23

jobs:
  lint:
    executor: linter
    steps:
      - checkout
      - run:  yamllint --no-warnings -d relaxed .

workflows:
  verify:
    jobs:
      - lint
      - orb-tools/pack
      - orb-tools/publish:
          name: publish
          context: orb-publishing
          filters:
            branches:
              only: master
          orb-path: src/orb.yml
          orb-ref: entur/salg-btd@dev:$CIRCLE_BRANCH
          requires:
            - lint
      - orb-tools/increment:
          name: release
          context: orb-publishing
          filters:
            branches:
              only: master
          orb-path: src/orb.yml
          orb-ref: entur/salg-btd
          requires:
            - publish
